gifting/urls.py
from django.urls import path
from . import views

app_name = "gifting"

urlpatterns = [
    path("", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("<str:pk>/", views.detail, name="detail"),
    path("<str:pk>/delete/", views.delete, name="delete"),
    path("<str:pk>/edit/", views.edit, name="edit"),
]

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views import defaults as default_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path("users/", include("users.urls")),
    path("gifting/", include("gifting.urls")),
    path("communities/", include("communities.urls")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

gifting/models.py
from django.contrib.gis.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from users.models import User
from .mixins import RandomIdMixin


class AdCategory(models.Model):
    """Category for Ads"""

    name = models.CharField(_("Name"), max_length=50)
    order = models.IntegerField(_("Order"), default="0")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Ad Category")
        verbose_name_plural = _("Ad Categories")
        ordering = ["order", "name"]


class Ad(RandomIdMixin, models.Model):
    """An Ad for either an offer or a wish"""

    TYPE_CHOICES = [("offer", _("Offer")), ("wish", _("Wish"))]

    random_id = models.CharField(
        _("Random Id"), max_length=8, primary_key=True, editable=False
    )
    title = models.CharField(_("Title"), max_length=255)
    type = models.CharField(
        _("Type"), choices=TYPE_CHOICES, max_length=5, default="offer"
    )
    description = models.TextField(_("Description"), blank=True)
    image = models.ImageField(_('image'), upload_to='gifting-images', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="ads",
        verbose_name=_("Owner"),
        null=True,
    )
    categories = models.ManyToManyField(
        AdCategory, related_name="ads", verbose_name=_("Categories"), blank=True
    )
    location_name = models.CharField(
        _("Location"), null=True, blank=True, max_length=255
    )
    location = models.PointField(
        _("Geo Location"), null=True, blank=True, geography=True
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self) -> str:
        return reverse("gifting:detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = _("Ad")
        verbose_name_plural = _("Ads")
        ordering = ["-created_at"]

gifting/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import InlineRadios, InlineCheckboxes
from crispy_forms.layout import Layout, Field, Fieldset as CrispyFieldset
from django.contrib.gis import forms

from .widgets import LocationWidget
from .models import Ad


class Fieldset(CrispyFieldset):
    def __init__(self, *args, **kwargs):
        self.text = kwargs.pop("header_text", "")
        super().__init__(*args, **kwargs)


class AdForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Fieldset("", InlineRadios("type"), InlineCheckboxes("categories")),
            Fieldset(
                _("Content"),
                Field("title"),
                Field("image"),
                Field("description"),
                header_text=_("Describe your wish or offer here"),
            ),
            Fieldset(_("Location"), Field("location_name"), Field("location")),
        )

    class Meta:
        model = Ad
        fields = (
            "type",
            "title",
            "description",
            "image",
            "categories",
            "location_name",
            "location",
        )
        widgets = {
            "type": forms.RadioSelect,
            "categories": forms.CheckboxSelectMultiple,
            "location_name": LocationWidget,
            "location": forms.OSMWidget(attrs={'map_width': '100%', 'map_height': 400, 'default_zoom': 1}),
        }

gifting/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.core.paginator import Paginator
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required

from .models import Ad
from .filters import AdFilter
from .forms import AdForm


def search(request):
    """Show all ads with filter ability"""
    f = AdFilter(request.GET, queryset=Ad.objects.all(), request=request)

    # pagination
    paginator = Paginator(f.qs, 50)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(request, "gifting/search.html", {"page_obj": page_obj, "f": f})


def detail(request, pk):
    """Show details for an Ad"""
    ad = get_object_or_404(Ad, pk=pk)
    return render(request, "gifting/ad_detail.html", {"ad": ad})


@login_required
def create(request):
    """Create a new Ad"""
    form = AdForm()
    if request.method == "POST":
        form = AdForm(request.POST, request.FILES)
        if form.is_valid():
            ad = form.save(commit=False)
            ad.owner = request.user
            form.save()
            messages.success(
                request, _("%(ad_type)s created") % {"ad_type": ad.get_type_display()}
            )
            return redirect(form.instance.get_absolute_url())
    return render(request, "gifting/ad_form.html", {"form": form})


def edit(request, pk):
    """Edit an existing Ad"""
    ad = get_object_or_404(Ad, pk=pk)
    if not ad.owner == request.user:
        return redirect("/users/login?next=%s" % request.path)

    form = AdForm(instance=ad)
    if request.method == "POST":
        form = AdForm(request.POST, request.FILES, instance=ad)
        if form.is_valid():
            form.save()
            ad = form.instance
            messages.success(request, _("changes saved"))
            return redirect(form.instance.get_absolute_url())
    return render(request, "gifting/ad_form.html", {"form": form, "ad": ad})


def delete(request, pk):
    ad = get_object_or_404(Ad, pk=pk)
    if not ad.owner == request.user:
        return redirect("/users/login?next=%s" % request.path)

    if request.method == "POST":
        ad.delete()
        messages.success(
            request, _("%(ad_type)s deleted") % {"ad_type": ad.get_type_display()}
        )
        return redirect(reverse("gifting:search"))
    else:
        return render(request, "gifting/ad_delete_confirm.html", {"ad": ad})

gifting/templates/gifting/_ad.html
{% load i18n %}
<a href="{% url "gifting:detail" ad.pk %}" class="relative w-full max-w-4xl group flex items-stretch justify-between my-5 sm:my-10 md:mb-20 bg-secondary bg-opacity-50 p-5 rounded-md hover:text-primary hover:shadow-lg">
  <div class="text-xs absolute bottom-0 right-0 rounded-full p-2 text-secondary{% if ad.get_type_display == "Offer" %} bg-primary{% else %} bg-purple{% endif %}">
        {{ ad.get_type_display }}
  </div>
  <div class="flex w-full">
    {% if ad.image %}
      <img class="flex-shrink-0 h-20 w-20 sm:h-32 sm:w-48" src="{{ ad.image.url }}">
    {% else %}
      <div class="flex-shrink-0 h-20 w-20 sm:h-32 sm:w-48 bg-primary"></div>
    {% endif %}

    <div class="pl-2 sm:pl-6 w-full">
      <i class="fa fa-map-marker text-primary"></i>
      {% if ad.distance != None %}
        <span class="text-xs">{{ ad.distance.km|floatformat:1 }} km {% trans "to" %}</span>
      {% endif %}
      <div class="text-xs inline hover:text-pr">{{ ad.location_name }}</div>
      <time class="text-xs text-gray-500 float-right mt-1"><i class="fa fa-calendar mr-2"></i>{{ ad.created_at }}</time>
      <div>
        {% for cat in ad.categories.all %}
          <span class="border mx-px py-px px-1 rounded-full text-xs text-secondary bg-primary">{{ cat.name }}</span>
        {% endfor %}
        <span class="font-serif sm:text-lg group-hover:text-primary">{{ ad.title }}</span>
      </div>
      <p class="text-sm text-brown">{{ ad.description|truncatewords:20 }}</p>
      <div>
        {% if ad.owner == request.user %}
          <span class="absolute bottom-5 border mx-px py-1 px-2 rounded text-xs text-secondary bg-purple"><i class="fa fa-user mr-2"></i>from me</span>
        {% else %}
          <span class="absolute bottom-5"><i class="fa fa-user mr-2"></i>{{ request.user.name }}</span>
        {% endif %}
      </div>
    </div>
  </div>
</a>

gifting/templates/gifting/_pagination.html
{% load i18n %}

{% if page_obj.paginator.num_pages > 1 %}
  <div class="py-4 mb-8 flex items-center justify-between">
    <div class="flex-1 flex justify-between sm:hidden">
      {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="relative inline-flex items-center px-4 py-2 border border-primary text-sm text-secondary leading-5 font-medium rounded-md bg-primary bg-opacity-75 hover:bg-opacity-100 hover:text-secondary focus:outline-none focus:shadow-outline-primary focus:border-primary active:bg-opacity-100 transition ease-in-out duration-150">
          <i class="fa fa-angle-left mr-2"></i>{% trans "Previous" %}
        </a>
      {% endif %}
      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="ml-auto relative inline-flex items-center px-4 py-2 border border-primary text-sm text-secondary leading-5 font-medium rounded-md bg-primary bg-opacity-75 hover:bg-opacity-100 hover:text-secondary focus:outline-none focus:shadow-outline-primary focus:border-primary active:bg-opacity-100 transition ease-in-out duration-150">
          <i class="fa fa-angle-right mr-2"></i>{% trans "Next" %}
        </a>
      {% endif %}
    </div>

    <div class="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
      <p class="text-sm leading-5">
        {% blocktrans with from=page_obj.start_index to=page_obj.end_index total=page_obj.paginator.count %}
          Showing {{ from }} to {{ to }} of {{ total }} results
        {% endblocktrans %}
      </p>
      <nav class="relative z-0 inline-flex shadow-sm">
        <a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %} class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-primary bg-primary bg-opacity-75 text-sm leading-5 font-medium text-secondary {% if page_obj.has_previous %}hover:bg-opacity-100{% endif %} hover:text-secondary focus:z-10 focus:outline-none focus:border-primary focus:shadow-outline-primary active:bg-opacity-100 transition ease-in-out duration-150" aria-label="Previous">
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
          </svg>
        </a>
        {% for page in page_obj.paginator.page_range %}
          <a {% if page != page_obj.number %}href="?page={{ page }}"{% endif %} class="-ml-px relative inline-flex items-center px-4 py-2 border border-primary bg-primary bg-opacity-75 hover:bg-opacity-100 hover:text-secondary text-sm leading-5 font-medium {% if page != page_obj.number %}hover:bg-opacity-100{% else %}bg-opacity-100{% endif %} focus:z-10 focus:outline-none focus:border-primary focus:shadow-outline-primary active:bg-opacity-100 transition ease-in-out duration-150">
            {{ page }}
          </a>
        {% endfor %}
        <a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %} class="-ml-px relative inline-flex items-center px-2 py-2 rounded-r-md border border-primary bg-primary bg-opacity-75 text-sm leading-5 font-medium text-secondary {% if page_obj.has_next %}hover:bg-opacity-100 hover:text-secondary{% endif %} focus:z-10 focus:outline-none focus:border-primary focus:shadow-outline-primary active:bg-opacity-100 transition ease-in-out duration-150" aria-label="Next">
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
          </svg>
        </a>
      </nav>
    </div>
  </div>
{% endif %}

gifting/templates/gifting/ad_delete_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% comment %} dont show navbar {% endcomment %}
{% block navbar %}
{% endblock navbar %}

{% block content %}

<div class="min-h-screen flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full">
    <form method="POST" class="bg-secondary bg-opacity-75 shadow rounded-md px-8 py-8 -mt-10">
      {% csrf_token %}

      <h1 class="text-xl text-purple font-bold mb-6">
        {% blocktrans with ad_type=ad.get_type_display %}
          Delete {{ ad_type }}?
        {% endblocktrans %}
      </h1>

      <p>
        {% blocktrans with ad_type=ad.get_type_display ad_title=ad.title %}
          Are you sure you want to delete the {{ ad_type }} <b>{{ ad_title }}</b>?
        {% endblocktrans %}
      </p>

      <div class="flex items-center justify-end -mx-5 mt-8">
        <a class="mx-5 btn flex" href="{{ ad.get_absolute_url }}"><i class="fa fa-ban mr-1"></i>{% trans "Cancel" %}</a>
        <button class="mx-5 btn btn-purple"><i class="fa fa-recycle mr-1"></i>{% trans "Delete" %}</button>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

gifting/templates/gifting/ad_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="mx-auto max-w-4xl mt-10 px-4">

  {% comment %} breadcrumbs {% endcomment %}
  <nav class="sm:hidden">
    <a href="{% url "gifting:search" %}" class="flex items-center text-sm leading-5 font-medium text-yellow hover:text-purple transition duration-150 ease-in-out">
      <svg class="flex-shrink-0 -ml-1 mr-1 h-5 w-5 text-yellow" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
      </svg>
      {% trans "Back" %}
    </a>
  </nav>
  <nav class="hidden sm:flex items-center text-sm leading-5 font-medium">
    <a href="{% url "gifting:search" %}" class="text-yellow hover:text-purple transition duration-150 ease-in-out">{% trans "Free Market" %}</a>
    <svg class="flex-shrink-0 mx-2 h-5 w-5 text-yellow" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
    </svg>
    <a href="{% url "gifting:search" %}?type={{ ad.type }}" class="text-yellow hover:text-purple transition duration-150 ease-in-out">{{ ad.get_type_display }}</a>
    <svg class="flex-shrink-0 mx-2 h-5 w-5 text-yellow" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
    </svg>
    <span class="text-primary">{{ ad.title }}</span>
  </nav>

  {% comment %} header {% endcomment %}
  <div class="mt-4 md:mt-10 md:flex md:items-center md:justify-between">
    <div class="flex-1 min-w-0">
      <div class="text-primary font-bold">{{ ad.get_type_display }}</div>
      <h1 class="sm:text-3xl sm:leading-9 sm:truncate">
        {{ ad.title }}
      </h1>
      <div class="my-1">
        {% if ad.owner == request.user %}
          <span class="border mx-px py-px px-1 rounded text-xs text-secondary bg-purple">from me</span>
        {% endif %}
        {% for cat in ad.categories.all %}
          <span class="border mx-px py-px px-1 rounded text-xs text-secondary bg-primary">{{ cat.name }}</span>
        {% endfor %}
        <span class="text-sm mx-2">{{ ad.location_name }}</span>
      </div>
    </div>

    {% if ad.owner == request.user %}
      <a href="{% url "gifting:delete" ad.pk %}" class="btn btn-purple flex mx-5">
        <i class="fa fa-recycle mr-1"></i>
        {% trans "Delete" %}
      </a>

      <div class="mt-4 flex-shrink-0 flex md:mt-0 md:ml-4">
        <span class="shadow-sm rounded-md">
          <a href="{% url "gifting:edit" ad.pk %}" class="btn inline-flex items-center">
            <i class="fa fa-edit mr-1"></i>
            {% trans "Edit" %}
          </a>
        </span>
      </div>
    {% endif %}
  </div>

  {% comment %} content {% endcomment %}
  <div class="mt-10">
    <p>{{ ad.description }}</p>
  </div>
</div>
{% endblock content %}

gifting/templates/gifting/ad_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags i18n %}

{% block content %}
<div class="mx-auto max-w-4xl px-4 mt-10">

  {% comment %} backlink {% endcomment %}
  <a href="{% if ad.pk %}{% url "gifting:detail" ad.pk %}{% else %}{% url "gifting:search" %}{% endif %}" class="btn flex items-center text-sm leading-5 font-medium">
    <svg class="flex-shrink-0 -ml-1 mr-1 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
    </svg>
    {% trans "Back" %}
  </a>

  {% comment %} heading {% endcomment %}
  <div class="mt-2 md:flex md:items-center md:justify-between border-b pb-4">
    <h1 class="leading-7 sm:text-3xl sm:leading-9 sm:truncatess">
      {% if ad.pk %}
        Edit {{ ad.get_type_display }} {{ ad.title }}
      {% else %}
        Create new Offer or Wish
      {% endif %}
    </h1>
  </div>
  
  {% comment %} form {% endcomment %}
  <form enctype="multipart/form-data" method="post" class="w-full my-10 form-control-w-full">
    {% csrf_token %}
    {% crispy form %}
    <div class="flex items-center justify-end -mx-5 my-5">
      <a class="mx-5 btn btn-red flex" href="{% if ad.pk %}{% url "gifting:detail" ad.pk %}{% else %}{% url "gifting:search" %}{% endif %}"><i class="fa fa-ban mr-1"></i>{% trans "Cancel" %}</a>
      {% if ad.pk %}
        <a href="{% url "gifting:delete" ad.pk %}" class="btn btn-purple"><i class="fa fa-recycle mr-1"></i>{% trans "Delete" %}</a>
      {% endif %}
      <button class="mx-5 btn btn-green" type="submit">
        <i class="fa fa-check mr-1"></i>{% trans "Save" %}
      </button>
    </div>
  </form>

  
</div>
{% endblock content %}

gifting/templates/gifting/search.html
{% extends 'base.html' %}
{% load crispy_forms_tags i18n %}

{% block content %}

{% comment %} filter bar {% endcomment %}
<div class="bg-secondary bg-opacity-50 shadow py-4">
  <form id="searchForm" x-data="" method="get" class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 js-submit-on-input">
    <div class="flex items-center flex-wrap -mx-2">

      {% comment %} search field {% endcomment %}
      <div class="relative w-full max-w-2xl my-2 mx-2">
        <div class="absolute ml-3 inset-y-0 flex items-center text-brown">
          <i class="fa fa-search text-primary opacity-75"></i>
        </div>
        <input type="text" value="{{ f.form.search.data|default:"" }}" class="pl-10 form-input w-full max-w-2xl" autocomplete="off" autofocus name="search">
      </div>

      {% comment %} location field {% endcomment %}
      <div class="relative my-2 mx-2" x-data="locationDropdown()">
        <div class="relative w-full max-w-2xl">
          <div class="absolute ml-3 inset-y-0 flex items-center text-primary">
            <i class="fa fa-map-marker-alt mr-1 text-primary opacity-75" onclick="getLocation()"></i>
          </div>
          <input id="location_name" x-ref="input" type="text" @input.debounce="onInput($event.target.value)" value="{{ f.form.location_name.data|default:"" }}" placeholder="Sort by Location" class="form-input w-full max-w-2xl pl-10" autocomplete="off" autofocus name="location_name">
        </div>
        <input x-ref="location" type="hidden" value="{{ f.form.location.data|default:"" }}" name="location">
        <div x-show.transition="open" @click.away="open = false" class="absolute inset-x-0 bg-secondary bg-opacity-50 shadow-lg text-xs py-3 rounded-b border-brown border-opacity-50 border-b border-l border-r">
          <ul class="list-none">
            <template x-for="res in results" :key="res">
              <li class="m-0"><a @click.prevent="onSelect(res)" href="#" class="block px-2 py-2 text-brown hover:bg-primary hover:text-secondary" x-text="res.display_name"></a></li>
            </template>
          </ul>
        </div>
      </div>
      <script>
        function locationDropdown() {
          return {
            results: [],
            open: false,
            onSelect(res) {
              this.$refs.location.value = res.lat + ',' + res.lon
              this.$refs.input.value = res.display_name
              this.open = false
              document.getElementById("searchForm").submit()
            },
            onInput(input) {
              if (input.length < 3) { results = []; return }
              fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=5&q=${input}`).then(res => res.json()).then(json => {
                this.open = true
                this.results = json
              })
            }
          }
        }
        
        var x = document.getElementById("location_name");

        function getLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(
                    // Success function
                    showPosition, 
                    // Error function
                    null, 
                    // Options. See MDN for details.
                    {
                       enableHighAccuracy: true,
                       timeout: 5000,
                       maximumAge: 0
                    });
            } else { 
                x.value = "{%trans 'Geolocation is not supported by this browser.' %}";
            }
        }

        function showPosition(position) {
            this.location.value=position.coords.latitude + "," + position.coords.longitude;
            x.value = "{%trans 'Current Location' %}";
              document.getElementById("searchForm").submit()
        }
      </script>

      <button class="btn m-2 hidden sm:block"><i class="fa fa-search mr-1"></i>{% trans "Search" %}</button>
    </div>

    <div x-on:input="$event.target.form.submit()">
      <div class="space-x-2 mb-2">
        {% for t in f.form.type %}
          <label class="inline-flex items-center">
            <input type="checkbox" name="{{ t.data.name }}" value="{{ t.data.value }}" {% if t.data.selected %}checked{% endif %} class="form-checkbox h-5 w-5">
            <span class="ml-2">{{ t.choice_label }}</span>
          </label>
        {% endfor %}
      </div>
      <div class="space-x-2 mb-2">
        {% for t in f.form.categories %}
          <label class="inline-flex items-center">
            <input type="checkbox" name="{{ t.data.name }}" value="{{ t.data.value }}" {% if t.data.selected %}checked{% endif %} class="form-checkbox h-5 w-5">
            <span class="ml-2">{{ t.choice_label }}</span>
          </label>
        {% endfor %}
      </div>
      {% if user.is_authenticated %}
        <div>
          <label class="inline-flex items-center">
            <input type="checkbox" name="{{ f.form.from_me.name }}" value="on" {% if f.form.from_me.data %}checked{% endif %} class="form-checkbox h-5 w-5">
            <span class="ml-2">{{ f.form.from_me.label }}</span>
          </label>
        </div>
      {% endif %}
    </div>
  </form>


</div>

<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

  <div class="my-10">
    {% comment %} Add button {% endcomment %}
    <a href="{% url "gifting:create" %}" class="btn inline-flex items-center shadow">
      <i class="fa fa-plus mr-1"></i>
      {% trans "Add your Wish or Offer" %}
    </a>
  </div>

  {% if page_obj %}
    <p>{% blocktrans with count=page_obj.paginator.count %}{{ count }} found{% endblocktrans %}</p>
    
    {% comment %} results {% endcomment %}
    {% for ad in page_obj %}
      {% include "./_ad.html" %}
    {% endfor %}

    {% include "./_pagination.html" %}
  {% else %}
    <p>{% trans "No results found" %}</p>
  {% endif %}

</div>



{% endblock content %}