urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views import defaults as default_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path("users/", include("users.urls")),
    path("gifting/", include("gifting.urls")),
    path("communities/", include("communities.urls")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    # password reset:
    path("password_reset/", views.PasswordResetView.as_view(), name="password_reset",),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("<slug>/", views.DetailView.as_view(), name="detail"),
]

users/models.py
from django.db import models
from django.core.mail import send_mail
from django.urls import reverse
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def get_by_natural_key(self, username):
        """When trying to find the user try email first, then username (for legacy users)"""
        try:
            return self.get(email=username)
        except self.model.DoesNotExist:
            return self.get(username=username)

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """user model

     * email is used for logging in
     * username is only used for legacy users, so they can still log in like on the old site
     * name is used instead of first_name and last_name
    """

    # username is only for legacy users and None/null by default, but unique for non-null values
    username = models.CharField(_("username"), unique=True, default=None, max_length=150, blank=True, null=True)

    email = models.EmailField(_("email address"), unique=True)
    first_name = None
    last_name = None
    name = models.CharField(_("name"), blank=True, max_length=255)
    image = models.ImageField(_('image'), upload_to='user-images', null=True, blank=True)
    about = models.TextField(_('About you'),  blank=True, null=True)
    ecobasa_what = models.TextField(_('What would you like to use ecobasa mainly for?'), blank=True, null=True)
    world = models.TextField(_('What do you do to make the world a better place?'), blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["name"]

    objects = UserManager()

    def get_absolute_url(self) -> str:
        return reverse("users:detail", kwargs={"email": self.email})

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from croppie.fields import CroppieField

from gifting.forms import Fieldset
from .models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = _("email address or name")
        self.error_messages["invalid_login"] = _("Credentials are not correct.")


class RegisterForm(forms.ModelForm):
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    image = CroppieField(
        options={
            "enableExif": True,
            "viewport": {
                "width": 200,
                "height": 200,
                "type": 'circle'
            },
            "boundary": {
                "width": 300,
                "height": 300
            }
        })

    class Meta:
        model = User
        fields = ["name", "email", "image"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].required = True
        self.fields["name"].widget.attrs["autofocus"] = True
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Fieldset(_("Personal Info"), Field("name"), Field("image"), header_text=_("Trust is the only currency in our gift-economy network, real names help to build trust"), ),
            Fieldset(
                _("Account"),
                Field("email"),
                Field("password"),
                header_text=_("Nessecary to logging in"),
            ),
        )

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get("password")
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except ValidationError as error:
                self.add_error("password", error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

users/views.py
from django.contrib.auth import views as django_views
from django.utils.translation import gettext_lazy as _
from django.shortcuts import redirect, reverse, render
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import logout as auth_logout, login as auth_login, authenticate
from django.views.generic.detail import DetailView
from .models import User

from .forms import RegisterForm, LoginForm


class LoginView(django_views.LoginView):
    template_name = "users/login.html"
    form_class = LoginForm

class DetailView(DetailView):
    model = User
    template_name = "users/detail.html"
    slug_field = "name"


def logout(request):
    """Logout user on POST requests only (more secure)"""
    if request.method == "POST":
        auth_logout(request)
        messages.success(request, _("You have been logged out."))
    return redirect(reverse("homepage:homepage"))


def register(request):
    """register a new user"""
    if request.user.is_authenticated:
        return redirect(reverse("homepage:homepage"))
    if request.method == "POST":
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get("email")
            name = form.cleaned_data.get("name")
            image = form.cleaned_data.get("image")
            raw_password = form.cleaned_data.get("password")
            user = authenticate(username=email, password=raw_password)
            auth_login(request, user)
            messages.success(request, _("Account created and logged in."))
            return redirect("homepage:homepage")
    else:
        form = RegisterForm()
    return render(request, "users/register.html", {"form": form})


class PasswordResetView(django_views.PasswordResetView):
    email_template_name = "users/password_reset/email.html"
    template_name = "users/password_reset/form.html"
    success_url = reverse_lazy("users:password_reset_done")


class PasswordResetDoneView(django_views.PasswordResetDoneView):
    template_name = "users/password_reset/done.html"


class PasswordResetConfirmView(django_views.PasswordResetConfirmView):
    success_url = reverse_lazy("users:password_reset_complete")
    template_name = "users/password_reset/confirm.html"


class PasswordResetCompleteView(django_views.PasswordResetCompleteView):
    template_name = "users/password_reset/complete.html"

users/templates/users/password_reset/complete.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}


{% block content %}
<div class="flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full">

    <h1 class="mt-6 text-center text-3xl leading-9">
      {% trans 'Password was reset' %}
    </h1>

    <div class="bg-secondary bg-opacity-75 shadow rounded-md px-8 py-8 mt-10 form-control-w-full">
      <p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

      <a class="btn block mt-5" href="{{ login_url }}">{% trans 'Log in' %}</a>
    </div>

  </div>
</div>
{% endblock %}

users/templates/users/password_reset/confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}


{% block content %}
<div class="flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full">

    <h1 class="mt-6 text-center text-3xl leading-9 font-bree text-gray-900">
      {% trans 'Reset your password' %}
    </h1>

    <div class="bg-secondary bg-opacity-75 shadow rounded-md px-8 py-8 mt-10 form-control-w-full">
      {% if validlink %}
        <p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

        <form method="post" class="mt-5">
          {% csrf_token %}
          {{ form | crispy }}
          <button class="btn w-full my-5">{% trans 'Change my password' %}</button>
        </form>

      {% else %}
        <h2 class="mb-4 font-bold text-xl">{% trans "Invalid Link" %}</h2>
        <p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>
        <a class="btn block w-full mt-6" href="{% url 'users:password_reset' %}">{% trans 'Reenter your email' %}</a>
      {% endif %}
    </div>

  </div>
</div>
{% endblock %}

users/templates/users/password_reset/done.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}


{% block content %}
<div class="flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full">

    <h1 class="mt-6 text-center text-3xl leading-9">
      {% trans 'Check your mail' %}
    </h1>

    <div class="bg-secondary bg-opacity-75 shadow rounded-md px-8 py-8 mt-10 form-control-w-full">
      <p class="mb-4">{% trans 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
      <p>{% trans 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
    </div>

  </div>
</div>
{% endblock %}

users/templates/users/password_reset/email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

users/templates/users/password_reset/form.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}

{% block content %}
<div class="flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full">

    <nav class="mb-10">
      <a href="{% url "users:login" %}" class="btn flex items-center text-sm leading-5 font-medium transition duration-150 ease-in-out">
        <svg class="flex-shrink-0 -ml-1 mr-1 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
        </svg>
        {% trans "Login" %}
      </a>
    </nav>

    <h1 class="mt-6 text-center text-3xl leading-9">
      {% trans 'Forgotten your password?' %}
    </h1>

    <div class="bg-secondary bg-opacity-75 shadow rounded-md px-8 py-8 mt-10 form-control-w-full">
      <p>{% trans 'Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.' %}</p>

      <form method="post" class="mt-8">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn w-full my-5">{% trans 'Reset my password' %}</button>
      </form>
    </div>

  </div>
</div>
{% endblock %}