urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views import defaults as default_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path("users/", include("users.urls")),
    path("gifting/", include("gifting.urls")),
    path("communities/", include("communities.urls")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    # password reset:
    path("password_reset/", views.PasswordResetView.as_view(), name="password_reset",),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("<slug>/", views.DetailView.as_view(), name="detail"),
]

users/models.py
from django.db import models
from django.core.mail import send_mail
from django.urls import reverse
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def get_by_natural_key(self, username):
        """When trying to find the user try email first, then username (for legacy users)"""
        try:
            return self.get(email=username)
        except self.model.DoesNotExist:
            return self.get(username=username)

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """user model

     * email is used for logging in
     * username is only used for legacy users, so they can still log in like on the old site
     * name is used instead of first_name and last_name
    """

    # username is only for legacy users and None/null by default, but unique for non-null values
    username = models.CharField(_("username"), unique=True, default=None, max_length=150, blank=True, null=True)

    email = models.EmailField(_("email address"), unique=True)
    first_name = None
    last_name = None
    name = models.CharField(_("name"), blank=True, max_length=255)
    image = models.ImageField(_('image'), upload_to='user-images', null=True, blank=True)
    about = models.TextField(_('About you'),  blank=True, null=True)
    ecobasa_what = models.TextField(_('What would you like to use ecobasa mainly for?'), blank=True, null=True)
    world = models.TextField(_('What do you do to make the world a better place?'), blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["name"]

    objects = UserManager()

    def get_absolute_url(self) -> str:
        return reverse("users:detail", kwargs={"email": self.email})

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from croppie.fields import CroppieField

from gifting.forms import Fieldset
from .models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = _("email address or name")
        self.error_messages["invalid_login"] = _("Credentials are not correct.")


class RegisterForm(forms.ModelForm):
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    image = CroppieField(
        options={
            "enableExif": True,
            "viewport": {
                "width": 200,
                "height": 200,
                "type": 'circle'
            },
            "boundary": {
                "width": 300,
                "height": 300
            }
        })

    class Meta:
        model = User
        fields = ["name", "email", "image"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].required = True
        self.fields["name"].widget.attrs["autofocus"] = True
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Fieldset(_("Personal Info"), Field("name"), Field("image"), header_text=_("Trust is the only currency in our gift-economy network, real names help to build trust"), ),
            Fieldset(
                _("Account"),
                Field("email"),
                Field("password"),
                header_text=_("Nessecary to logging in"),
            ),
        )

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get("password")
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except ValidationError as error:
                self.add_error("password", error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

users/views.py
from django.contrib.auth import views as django_views
from django.utils.translation import gettext_lazy as _
from django.shortcuts import redirect, reverse, render
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import logout as auth_logout, login as auth_login, authenticate
from django.views.generic.detail import DetailView
from .models import User

from .forms import RegisterForm, LoginForm


class LoginView(django_views.LoginView):
    template_name = "users/login.html"
    form_class = LoginForm

class DetailView(DetailView):
    model = User
    template_name = "users/detail.html"
    slug_field = "name"


def logout(request):
    """Logout user on POST requests only (more secure)"""
    if request.method == "POST":
        auth_logout(request)
        messages.success(request, _("You have been logged out."))
    return redirect(reverse("homepage:homepage"))


def register(request):
    """register a new user"""
    if request.user.is_authenticated:
        return redirect(reverse("homepage:homepage"))
    if request.method == "POST":
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get("email")
            name = form.cleaned_data.get("name")
            image = form.cleaned_data.get("image")
            raw_password = form.cleaned_data.get("password")
            user = authenticate(username=email, password=raw_password)
            auth_login(request, user)
            messages.success(request, _("Account created and logged in."))
            return redirect("homepage:homepage")
    else:
        form = RegisterForm()
    return render(request, "users/register.html", {"form": form})


class PasswordResetView(django_views.PasswordResetView):
    email_template_name = "users/password_reset/email.html"
    template_name = "users/password_reset/form.html"
    success_url = reverse_lazy("users:password_reset_done")


class PasswordResetDoneView(django_views.PasswordResetDoneView):
    template_name = "users/password_reset/done.html"


class PasswordResetConfirmView(django_views.PasswordResetConfirmView):
    success_url = reverse_lazy("users:password_reset_complete")
    template_name = "users/password_reset/confirm.html"


class PasswordResetCompleteView(django_views.PasswordResetCompleteView):
    template_name = "users/password_reset/complete.html"

users/templates/users/detail.html
{% extends 'base.html' %}
{% load i18n embed_video_tags %}

{% block content %}
<div class="mx-auto max-w-7xl mt-10 px-4 pb-10">
	<h1>{{ user.name }}</h1>
	<div class="sm:grid sm:grid-cols-4 sm:gap-6">
		<div>
			{% if user.image %}
	        	<img class="object-fill rounded-full mt-15" src="{{ user.image.url }}" alt="">
	        {% else %}
	        	<i class="fa fa-user text-6xl text-primary rounded-full border border-dashed border-primary p-10 mt-15"></i>
	        {% endif %}
	        <a class="btn block mt-10" href="#"><i class="fa fa-envelope mr-2"></i>{% trans "Message" %}</a>
		</div>
		<div class="sm:col-span-3">
			<h2>{% trans "About me" %}</h2>
			<p>{{ user.about }}</p>
			<h2>{% trans "What do you do to make the world a better place?" %}</h2>
			<p>{{ user.world }}</p>
			<h2>{% trans "What would you like to use ecobasa mainly for?" %}</h2>
			<p>{{ user.ecobasa_what }}</p>
		</div>
	</div>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags i18n %}

{% block content %}

<div class="flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full">

    <div>
      <a href="/"><svg class="fill-current text-primary mx-auto h-14 w-14" viewbox="0 0 180 205"><path d="M83 199.78C72.2 191.8 63.73 177 61.5 162.27c-.55-3.72-.42-4.57.67-4.18.75.27 7.26 2.07 14.47 4l13.1 3.52 11.75-3.01c6.47-1.66 12.58-3.45 13.59-4 2.97-1.58 3.14-1.25 2.4 4.78-1.79 14.67-9 27.71-20.21 36.5-3.34 2.61-6.44 4.74-6.9 4.73-.46 0-3.77-2.18-7.36-4.83zm-67.64-40.66a68.23 68.23 0 01-10.77-3.37L0 153.72l.59-4.3c1.78-13.09 4.43-20.21 10.9-29.28 5.05-7.08 15.36-16.38 15.9-14.34.35 1.32 2.1 8.16 5.41 21.14 1.68 6.6 2.07 7.14 11.99 16.81 5.64 5.5 10.25 10.19 10.25 10.42 0 1-7.94 4.3-12.8 5.33-6.95 1.48-19.15 1.3-26.88-.38zm119.21-.1c-3.28-.8-6.95-2.1-8.16-2.89-2.16-1.41-1.98-1.65 8.54-11.72 9.6-9.2 10.82-10.75 11.5-14.72a58.48 58.48 0 012.74-9.44 52.28 52.28 0 002.66-10.33l.69-5.33 6.15 4.98c10.96 8.88 18.94 23.86 20.1 37.72l.5 6.16-4.23 2.17c-9.38 4.78-28.21 6.37-40.49 3.4zM21.6 94.57C9.56 84.63 1.04 67.75 1.04 53.88c0-4.14.18-4.4 4.28-6.16 12.6-5.4 35.1-5.6 47.53-.4l3.5 1.46-8.41 8.48c-4.62 4.66-9.86 9.39-11.65 10.5-2.84 1.77-3.25 2.57-3.25 6.27 0 2.34-1.13 7.55-2.5 11.6-1.38 4.04-2.5 8.62-2.5 10.17 0 1.56-.35 2.83-.77 2.83-.42 0-2.98-1.83-5.68-4.06zm130.45 1.03c0-1.67-.9-5.72-2.01-9-1.1-3.29-2.48-8.1-3.05-10.72-.86-3.93-2.37-6.14-8.74-12.75-4.24-4.4-9.23-9.2-11.1-10.65l-3.4-2.64 3.1-1.6c5.5-2.85 14.4-4.61 23.27-4.61 10.68 0 17.65 1.27 24.7 4.5l5.4 2.47-.63 4.26c-2 13.43-5.32 22.15-11.6 30.46-3.5 4.63-13.46 13.3-15.28 13.3-.36 0-.66-1.36-.66-3.02zM62.42 41.05c1.86-15.82 10.16-29.5 23.44-38.64 4.02-2.77 4.6-2.9 7.02-1.65 4.7 2.42 15.57 14.2 18.82 20.37a67.53 67.53 0 016.78 21.37c.56 3.92.44 4.29-1.16 3.6-.98-.43-6.5-2.04-12.28-3.58-5.78-1.54-11.3-3.28-12.27-3.87a3.42 3.42 0 00-3.63-.07c-1.03.54-6 1.91-11.06 3.04-5.06 1.13-10.8 2.72-12.76 3.53l-3.56 1.5.66-5.6z"/></svg></a>
      <h1 class="mt-6 text-center text-3xl leading-9">
        {% trans "Log in to your ecobasa account" %}
      </h1>
      <p class="mt-2 text-center text-base leading-5">
        <a href="{% url "users:register" %}" class="font-bold focus:outline-none focus:underline">
          {% trans "Or create a new account" %}
        </a>
      </p>
    </div>

    <form method="POST" class="bg-secondary bg-opacity-75 shadow rounded-md px-8 py-8 mt-10 form-control-w-full">
      {% csrf_token %}
      
      {{ form | crispy }}

      <div class="flex justify-end">
        <a href="{% url "users:password_reset" %}" class="text-sm text-primary">{% trans "Forgot your password?" %}</a>
      </div>

      <button class="btn w-full my-5"><i class="fa fa-sign-in-alt mr-1"></i>{% trans "Log in" %}</button>
    </form>
  </div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}

{% block content %}
<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 mt-10">
  {% comment %} breadcrumbs {% endcomment %}
  <nav class="my-5">
    <a href="{% url "users:login" %}" class="btn flex items-center text-sm leading-5 font-medium transition duration-150 ease-in-out">
      <svg class="flex-shrink-0 -ml-1 mr-1 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
      </svg>
      {% trans "Login" %}
    </a>
  </nav>

  <h1 class="text-2xl">{% trans "Register for an account at ecobasa" %}</h1>

  <form enctype="multipart/form-data" method="post" class="w-full my-10 form-control-w-full">
    <div id="cropper" class="ml-3"></div>
    {% crispy form %}
    <div class="flex items-center justify-end -mx-5 my-5">
      <a class="mx-5 btn btn-purple flex" href="{% url "users:login" %}"><i class="fa fa-ban mr-1"></i>{% trans "Cancel" %}</a>
      <button class="btn mx-5" type="submit">
        <i class="fa fa-user-check mr-1"></i>
        {% trans "Register" %}
      </button>
    </div>
  </form>

</div>
{% endblock content %}

{% block javascript %}
  {{ form.media }}
{% endblock javascript %}