gifting/urls.py
from django.urls import path
from . import views

app_name = "gifting"

urlpatterns = [
    path("", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("<str:pk>/", views.detail, name="detail"),
    path("<str:pk>/delete/", views.delete, name="delete"),
    path("<str:pk>/edit/", views.edit, name="edit"),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("support/", views.support, name="support"),
]

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views import defaults as default_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path("users/", include("users.urls")),
    path("gifting/", include("gifting.urls")),
    path("communities/", include("communities.urls")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    # password reset:
    path("password_reset/", views.PasswordResetView.as_view(), name="password_reset",),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("<slug>/", views.DetailView.as_view(), name="detail"),
]

templates/_footer.html
{% load static i18n %}
<footer class="flex justify-between items-center bg-primary bg-opacity-75 text-secondary font-bold px-4 shadow-sm border-b h-12">
	<div class="w-1/3 xl:w-1/5">
		<a class="mr-1 md:mr-4" href="/newsletter"><i class="fa fa-envelope mr-2"></i><span class="hidden md:inline">{% trans "Newsletter" %}</span></a>
		<a href="/contact"><i class="fa fa-at mr-2"></i><span class="hidden md:inline">{% trans "Contact ecobasa" %}</span></a>
	</div>
	<div class="w-1/3 xl:w-1/5 text-center">

		<div x-data="{ tooltip: false }" class="relative z-30 inline-flex">
		    <div id="license" class="cursor-pointer" rel="license" x-on:click="tooltip = true" x-on:click.away="tooltip = false"><img class="mx-auto" alt="Creative Commons License BY-NC-SA 4.0" style="border-width:0;" src="{% static "images/cc-license-bright.png" %}" /></div>
		    <div class="relative" x-cloak x-show.transition.origin.top="tooltip">
				<div class="absolute top-0 z-50 w-64 p-2 -mt-1 text-sm text-brown transform -translate-x-1/2 -translate-y-full bg-secondary bg-opacity-75 rounded-lg shadow-lg">
					<span xmlns:dct='http://purl.org/dc/terms/' href='http://purl.org/dc/dcmitype/StillImage' property='dct:title' rel='dct:type'><a class="text-yellow"xmlns:cc='http://creativecommons.org/ns#' href='https://ecobasa.org' property='cc:attributionName' rel='cc:attributionURL'>ecobasa.org</a></span> is licensed under a <a class="text-yellow" rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>
				</div>
				<svg class="absolute z-10 w-6 h-6 text-orange-500 transform -translate-x-12 -translate-y-3 fill-current stroke-current" width="8" height="8">
					<rect x="12" y="-10" width="8" height="8" transform="rotate(45)" />
				</svg>
			</div>
		</div>
	</div>
	<div class="w-1/3 xl:w-1/5">
		<a class="float-right" href="https://www.facebook.com/ecobasa/"><i class="fab fa-facebook-square md:text-3xl"></i></a>
		<a class="float-right" href="https://www.youtube.com/channel/UC9P0vCR7DDPHly81cNQ_vyw"><i class="fab fa-youtube mx-6 md:text-3xl"></i></a>
		<a class="float-right" href="https://github.com/ecobasa/ecobasa/"><i class="fab fa-github md:text-3xl"></i></a>
	</div>
</footer>

templates/_messages.html
{% if messages %}
  <div class="mx-auto max-w-7xl fixed inset-0 z-50 sm:mt-12 flex items-end justify-center px-4 py-6 pointer-events-none sm:p-6 sm:items-start sm:justify-end">
    {% for message in messages %}
      <div x-show="open" x-data="{ open: true }"
          x-transition:enter="transform ease-out duration-300 transition"
          x-transition:enter-start="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
          x-transition:enter-end="translate-y-0 opacity-100 sm:translate-x-0"
          x-transition:leave="transition ease-in duration-100"
          x-transition:leave-start="opacity-100"
          x-transition:leave-end="opacity-0"
          class="w-full bg-opacity-50 border shadow-lg rounded-lg pointer-events-auto 
          {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
          bg-green text-secondary border-green
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
          bg-red text-secondary border-red
          {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
          bg-yellow text-secondary border-yellow
          {% else %}
          bg-secondary text-brown border-third
          {% endif %}
          ">
        <div class="rounded-lg shadow-xs overflow-hidden">
          <div class="p-4">
            <div class="flex items-start">
              <div class="flex-shrink-0">
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                  {% comment %} checkmark {% endcomment %}
                  <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                  {% comment %} exclamation mark {% endcomment %}
                  <svg class="h-6 w-6" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                  {% comment %} warnin sign {% endcomment %}
                  <svg class="h-6 w-6" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                {% endif %}
              </div>
              <div class="ml-3 w-0 flex-1 pt-0.5">
                <p class="text-sm leading-5 font-medium">
                  {{ message }}
                </p>
              </div>
              <div class="ml-4 flex-shrink-0 flex">
                <button @click="open = false" class="inline-flex focus:outline-none focus:text-dark-brown transition ease-in-out duration-150">
                  <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endif %}

templates/_navbar.html
{% load i18n %}

{% with request.resolver_match.view_name as view_name and request.resolver_match.namespace as namespace %}

{% block css %}
<script type="text/css">
  
</script>
{% endblock %}

<nav class="bg-primary bg-opacity-75 text-secondary font-bold shadow-sm border-b z-40" x-data="{ mobileMenuOpen: false }">
  <div class="mx-auto px-4">
    <div class="flex justify-between h-16">
      <div class="flex">
        {% comment %} Logo {% endcomment %}
        <div class="flex-shrink-0 flex items-center md:mr-6">
          <a href="/" class="flex items-center">
            <svg class="fill-current h-7 w-7 mt-1 mr-2" viewbox="0 0 180 205"><path d="M83 199.78C72.2 191.8 63.73 177 61.5 162.27c-.55-3.72-.42-4.57.67-4.18.75.27 7.26 2.07 14.47 4l13.1 3.52 11.75-3.01c6.47-1.66 12.58-3.45 13.59-4 2.97-1.58 3.14-1.25 2.4 4.78-1.79 14.67-9 27.71-20.21 36.5-3.34 2.61-6.44 4.74-6.9 4.73-.46 0-3.77-2.18-7.36-4.83zm-67.64-40.66a68.23 68.23 0 01-10.77-3.37L0 153.72l.59-4.3c1.78-13.09 4.43-20.21 10.9-29.28 5.05-7.08 15.36-16.38 15.9-14.34.35 1.32 2.1 8.16 5.41 21.14 1.68 6.6 2.07 7.14 11.99 16.81 5.64 5.5 10.25 10.19 10.25 10.42 0 1-7.94 4.3-12.8 5.33-6.95 1.48-19.15 1.3-26.88-.38zm119.21-.1c-3.28-.8-6.95-2.1-8.16-2.89-2.16-1.41-1.98-1.65 8.54-11.72 9.6-9.2 10.82-10.75 11.5-14.72a58.48 58.48 0 012.74-9.44 52.28 52.28 0 002.66-10.33l.69-5.33 6.15 4.98c10.96 8.88 18.94 23.86 20.1 37.72l.5 6.16-4.23 2.17c-9.38 4.78-28.21 6.37-40.49 3.4zM21.6 94.57C9.56 84.63 1.04 67.75 1.04 53.88c0-4.14.18-4.4 4.28-6.16 12.6-5.4 35.1-5.6 47.53-.4l3.5 1.46-8.41 8.48c-4.62 4.66-9.86 9.39-11.65 10.5-2.84 1.77-3.25 2.57-3.25 6.27 0 2.34-1.13 7.55-2.5 11.6-1.38 4.04-2.5 8.62-2.5 10.17 0 1.56-.35 2.83-.77 2.83-.42 0-2.98-1.83-5.68-4.06zm130.45 1.03c0-1.67-.9-5.72-2.01-9-1.1-3.29-2.48-8.1-3.05-10.72-.86-3.93-2.37-6.14-8.74-12.75-4.24-4.4-9.23-9.2-11.1-10.65l-3.4-2.64 3.1-1.6c5.5-2.85 14.4-4.61 23.27-4.61 10.68 0 17.65 1.27 24.7 4.5l5.4 2.47-.63 4.26c-2 13.43-5.32 22.15-11.6 30.46-3.5 4.63-13.46 13.3-15.28 13.3-.36 0-.66-1.36-.66-3.02zM62.42 41.05c1.86-15.82 10.16-29.5 23.44-38.64 4.02-2.77 4.6-2.9 7.02-1.65 4.7 2.42 15.57 14.2 18.82 20.37a67.53 67.53 0 016.78 21.37c.56 3.92.44 4.29-1.16 3.6-.98-.43-6.5-2.04-12.28-3.58-5.78-1.54-11.3-3.28-12.27-3.87a3.42 3.42 0 00-3.63-.07c-1.03.54-6 1.91-11.06 3.04-5.06 1.13-10.8 2.72-12.76 3.53l-3.56 1.5.66-5.6z"/></svg>
            <span class="font-serif font-normal text-3xl mb-1">ecobasa.org</span>
          </a>
        </div>
        {% comment %} Desktop Menu {% endcomment %}
        <div class="hidden sm:ml-6 sm:flex">
          <a href="{% url "gifting:search" %}" class="{% if namespace == "gifting" %}border-brown text-brown{% else %}border-transparent hover:border-brown{% endif %} ml-8 inline-flex items-center px-1 pt-1 border-b-2 border-transparent leading-5 focus:outline-none focus:text-brown focus:border-brown transition duration-150 ease-in-out">
            <i class="fa fa-recycle mr-2"></i>
            {% trans "Free Market" %}
          </a>
          <a href="#" class="ml-8 inline-flex items-center px-1 pt-1 border-b-2 border-transparent leading-5 hover:border-brown focus:outline-none transition duration-150 ease-in-out">
            <i class="fa fa-home mr-2"></i>
            {% trans "Communities" %}
          </a>
          <a href="{% url "homepage:support" %}" class="{% if request.path == "/support/" %}border-brown text-brown{% else %}border-transparent hover:border-brown{% endif %} ml-8 inline-flex items-center px-1 pt-1 border-b-2 border-transparent leading-5 focus:outline-none focus:text-brown focus:border-brown transition duration-150 ease-in-out">
            <i class="fa fa-heart mr-2"></i>
            {% trans "Support" %}
          </a>
        </div>
      </div>
      {% if user.is_authenticated %}
        <div class="hidden sm:ml-6 sm:flex sm:items-center">
          {% comment %} Notification Bell {% endcomment %}
          <button class="p-1 border-2 border-transparent rounded-full hover:text-brown focus:outline-none focus:text-brown transition duration-150 ease-in-out" aria-label="Notifications">
            <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
            </svg>
          </button>

          {% comment %} Profile dropdown {% endcomment %}
          <div class="ml-3 relative" x-data="{ open: false }">
            <div>
              <button @click="open = true" class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition duration-150 ease-in-out" id="user-menu" aria-label="User menu" aria-haspopup="true">
               {% if user.image %}
                <img class="h-8 w-8 rounded-full" src="{{ user.image.url }}" alt="">
               {% else %}
                <i class="fa fa-user text-xl text-primary rounded-full bg-secondary p-3"></i>
               {% endif %}
              </button>
            </div>
            {% comment %} dropdown {% endcomment %}
            <div x-show="open" @click.away="open = false"
                  x-transition:enter="transition ease-out duration-200"
                  x-transition:enter-start="opacity-0 transform scale-95"
                  x-transition:enter-end="opacity-100 transform scale-100"
                  x-transition:leave="transition ease-in duration-75"
                  x-transition:leave-start="opacity-100 transform scale-100"
                  x-transition:leave-end="opacity-0 transform scale-95"
                  class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg z-40">
              <div class="py-1 rounded-md bg-primary bg-opacity-75 shadow-xs">
                <a href="{% url "users:detail" slug=user.name %}" class="block px-4 py-2 text-sm leading-5 text-secondary hover:bg-secondary focus:outline-none focus:bg-secondary transition duration-150 ease-in-out">
                  <i class="fa fa-user mr-2"></i>
                  {% trans "Your Profile" %}
                </a>
                <a href="#" class="block px-4 py-2 text-sm leading-5 text-secondary hover:bg-secondary focus:outline-none focus:bg-secondary transition duration-150 ease-in-out">
                  <i class="fa fa-cog mr-2"></i>
                  {% trans "Settings" %}
                </a>
                <form action="{% url "users:logout" %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="w-full text-left block px-4 py-2 text-sm font-bold leading-5 text-secondary hover:bg-secondary focus:outline-none focus:bg-secondary hover:text-brown focus:text-brown transition duration-150 ease-in-out">
                  <i class="fa fa-sign-out-alt mr-2"></i>
                  {% trans "Log out" %}
                </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      {% else %}
        {% comment %} Login button {% endcomment %}
        <div class="flex-shrink-0 hidden sm:ml-6 sm:flex sm:items-center">
          <a href="{% url "users:login" %}?next={{ request.path }}" class="relative inline-flex items-center px-4 py-2 border border-transparent border-secondary text-sm leading-5 rounded-md hover:text-primary shadow-sm hover:bg-secondary focus:outline-none focus:border-secondary focus:shadow-outline-brown active:bg-secondary transition ease-in-out duration-150">
            <i class="fa fa-sign-in-alt mr-2"></i>
            <span>{% trans "Log in" %}</span>
          </a>
        </div>
      {% endif %}
      <div class="-mr-2 flex items-center sm:hidden">
        {% comment %} mobile menu button {% endcomment %}
        <button @click="mobileMenuOpen = !mobileMenuOpen" class="inline-flex items-center justify-center p-2 rounded-md focus:outline-none">
          <svg x-show="!mobileMenuOpen" class="block h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <svg x-show="mobileMenuOpen" class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>

  {% comment %} mobile menu {% endcomment %}
  <div x-show="mobileMenuOpen"
      x-transition:enter="transition ease-out duration-200"
      x-transition:enter-start="opacity-0 transform scale-y-95"
      x-transition:enter-end="opacity-100 transform scale-y-100"
      x-transition:leave="transition ease-in duration-75"
      x-transition:leave-start="opacity-100 transform scale-y-100"
      x-transition:leave-end="opacity-0 transform scale-y-95"
      class="sm:hidden origin-top-right">
    <div class="pt-2 pb-3">
      <a href="{% url "gifting:search" %}" class="mt-1 block pl-3 pr-4 py-2 border-l-4 border-transparent {% if namespace == "gifting" %}border-brown text-brown focus:text-brown focus:border-brown{% else %}text-secondary hover:text-primary hover:bg-secondary hover:border-brown focus:text-brown focus:bg-secondary focus:border-brown{% endif %} text-base focus:outline-none"><i class="fa fa-recycle mr-2"></i>{% trans "Free Market" %}</a>
      <a href="#" class="mt-1 block pl-3 pr-4 py-2 border-l-4 border-transparent {% if namespace == "gifting" %}border-brown text-brown focus:text-brown focus:border-brown{% else %}text-secondary hover:text-primary hover:bg-secondary hover:border-brown focus:text-brown focus:bg-secondary focus:border-brown{% endif %} text-base focus:outline-none"><i class="fa fa-home mr-2"></i>{% trans "Communities" %}</a>
      <a href="{% url "homepage:support" %}" class="mt-1 block pl-3 pr-4 py-2 border-l-4 border-transparent {% if request.path == "/support/" %}border-brown text-brown focus:text-brown focus:border-brown{% else %}text-secondary hover:text-primary hover:bg-secondary hover:border-brown focus:text-brown focus:bg-secondary focus:border-brown{% endif %} text-base focus:outline-none"><i class="fa fa-recycle mr-2"></i>{% trans "Support" %}</a>
    </div>

    {% if user.is_authenticated %}
      <div class="pt-4 pb-3 border-t border-gray-200">
        <div class="flex items-center px-4">
          <div class="flex-shrink-0">
             {% if user.image %}
              <img class="h-8 w-8 rounded-full" src="{{ user.image.url }}" alt="">
             {% else %}
              <i class="fa fa-user text-3xl text-primary rounded-full bg-secondary p-3"></i>
             {% endif %}
          </div>
          <div class="ml-3">
            <div class="text-base font-bold leading-6">{{ user.name }}</div>
            <div class="text-sm font-medium leading-5">{{ user.email }}</div>
          </div>
        </div>
        <div class="mt-3" role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
          <a href="#" class="block px-4 py-2 text-base text-secondary hover:text-primary hover:bg-secondary focus:text-primary focus:bg-secondary" role="menuitem"><i class="fa fa-user mr-2"></i>{% trans "Your Profile" %}</a>
          <a href="#" class="mt-1 block px-4 py-2 text-base text-secondary hover:text-primary hover:bg-secondary focus:text-primary focus:bg-secondary" role="menuitem"><i class="fa fa-cog mr-2"></i>{% trans "Settings" %}</a>
          <a href="{% url "users:logout" %}" class="mt-1 block px-4 py-2 text-base text-secondary hover:text-primary hover:bg-secondary focus:text-primary focus:bg-secondary" role="menuitem"><i class="fa fa-sign-out-alt mr-2"></i>{% trans "Log out" %}</a>
        </div>
      </div>
    {% else %}
      <a href="{% url "users:login" %}?next={{ request.path }}" class="mt-1 block px-4 py-2 text-base text-secondary hover:text-primary hover:bg-secondary focus:text-primary focus:bg-secondary">
            <i class="fa fa-sign-in-alt mr-2"></i>
            <span>{% trans "Log in" %}</span>
          </a>
    {% endif %}
  </div>
</nav>

{% endwith %}

templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="de" class="h-full">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}ecobasa{% endblock head_title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block meta_description %}The sustainable gift-economy community{% endblock %}">
    <link rel="shortcut icon" href="{% static "images/favicon.ico" %}">

    {% block css %}
      <link rel="stylesheet" href="{% static 'styles/base.min.css' %}">
      <link rel="stylesheet" href="{% static '@fortawesome/fontawesome-free/css/all.css' %}">
    {% endblock %}

    {% block extrahead %}{% endblock %}
  </head>

  <body class="font-sans text-brown antialiased min-h-full flex flex-col">

    <div class="flex-auto">
      {% block navbar %}
        {% include "_navbar.html" %}
      {% endblock navbar %}

      <div class="flex items-stretch justify-between">

        <div class="w-full">

          <div class="">
            {% block content %}{% endblock content %}
          </div>
        </div>
      </div>
    </div>

    {% include "_messages.html" %}
    
    {% include "_footer.html" %}

    {% block javascript %}
      <script type="text/javascript" src="{% static 'alpinejs/dist/alpine.js' %}"></script>
    {% endblock javascript %}
  </body>

</html>